name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - run: yarn install
      - run: ci=true yarn test
      - run: yarn build
      - run: | #run surge token to obtain deployment token
          npm install --global surge
      - run: surge ./build superreaction.surge.sh --token ${{ secrets.SURGE_TOKEN }}
