
name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    - name: Run tests
    - run: CI=true yarn test

    - name: build Project 
    - run: yarn build

    - name: Deploy to Surge
    - run: | 
        npm install --global surge
        surge public superreaction.surge.sh

